#!/usr/bin/env python3
"""
Compile images into a CBZ (Comic Book Zip) archive.
CBZ is a widely supported format for comic readers.
"""

import os
import sys
import json
import zipfile
from pathlib import Path
from PIL import Image
import re

def load_scene_descriptions(imaginize_dir):
    """Load scene descriptions from Chapters.md file."""
    descriptions = {}
    chapters_file = Path(imaginize_dir) / 'Chapters.md'

    if not chapters_file.exists():
        return descriptions

    try:
        with open(chapters_file, 'r', encoding='utf-8') as f:
            content = f.read()

        lines = content.split('\n')
        i = 0

        while i < len(lines):
            line = lines[i].strip()

            scene_match = re.match(r'^####\s+Scene\s+(\d+)', line)
            if scene_match:
                for j in range(i+1, min(i+20, len(lines))):
                    if '**Visual Elements:**' in lines[j]:
                        desc_line = lines[j].split('**Visual Elements:**', 1)[1].strip()
                        full_desc = desc_line
                        k = j + 1
                        while k < len(lines) and lines[k].strip() and not lines[k].startswith('**'):
                            full_desc += ' ' + lines[k].strip()
                            k += 1

                    if '**Generated Image:**' in lines[j] or 'View Image' in lines[j]:
                        match = re.search(r'chapter_(\d+)_scene_(\d+)\.png', lines[j])
                        if match:
                            descriptions[(match.group(1), match.group(2))] = full_desc.strip() if 'full_desc' in dir() else ''
                        break
            i += 1

    except Exception as e:
        print(f"⚠️  Warning: Could not parse Chapters.md: {e}")

    return descriptions

def collect_images(base_dir):
    """Collect all PNG images sorted by chapter and scene."""
    images = []
    base_path = Path(base_dir)

    if base_path.name.startswith('imaginize_'):
        for img_file in base_path.glob('*.png'):
            images.append(str(img_file))
    else:
        for img_dir in base_path.glob('imaginize_*'):
            if img_dir.is_dir():
                for img_file in img_dir.glob('*.png'):
                    images.append(str(img_file))

    def sort_key(path):
        filename = Path(path).stem
        match = re.search(r'chapter_(\d+)_scene_(\d+)', filename)
        if match:
            return (int(match.group(1)), int(match.group(2)))
        return (999, 999)

    images.sort(key=sort_key)
    return images

def create_comicinfo_xml(title, author, num_pages):
    """Create ComicInfo.xml for CBZ metadata."""
    return f'''<?xml version="1.0" encoding="utf-8"?>
<ComicInfo xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Title>{title}</Title>
  <Writer>{author}</Writer>
  <Publisher>imaginize</Publisher>
  <Genre>AI Illustrated</Genre>
  <PageCount>{num_pages}</PageCount>
  <Notes>Generated by imaginize - AI-powered book illustration</Notes>
  <Web>https://github.com/tribixbite/imaginize</Web>
</ComicInfo>'''

def create_cbz(images, output_path, title="Illustrated Book", author="Unknown", imaginize_dir=None):
    """
    Create CBZ archive from images.

    Args:
        images: List of image paths
        output_path: Output CBZ path
        title: Book title
        author: Author name
        imaginize_dir: Path to imaginize directory
    """
    print(f"📦 Creating CBZ archive with {len(images)} images...")

    with zipfile.ZipFile(output_path, 'w', zipfile.ZIP_DEFLATED) as cbz:
        # Add ComicInfo.xml
        comic_info = create_comicinfo_xml(title, author, len(images))
        cbz.writestr('ComicInfo.xml', comic_info)

        # Add images with numbered filenames for proper ordering
        for i, img_path in enumerate(images):
            # Extract chapter/scene info for naming
            filename = Path(img_path).stem
            match = re.search(r'chapter_(\d+)_scene_(\d+)', filename)
            if match:
                new_name = f"{i:04d}_ch{match.group(1)}_sc{match.group(2)}.png"
            else:
                new_name = f"{i:04d}_{filename}.png"

            cbz.write(img_path, new_name)

            if (i + 1) % 10 == 0:
                print(f"   Added {i + 1}/{len(images)} images...")

    size_mb = Path(output_path).stat().st_size / (1024 * 1024)
    print(f"\n✅ CBZ created: {output_path}")
    print(f"   Total images: {len(images)}")
    print(f"   File size: {size_mb:.1f} MB")

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description='Compile images into CBZ comic archive')
    parser.add_argument('base_dir', help='Base directory or specific imaginize_* directory')
    parser.add_argument('output_file', help='Output CBZ filename')
    parser.add_argument('--title', default='Illustrated Book', help='Book title')
    parser.add_argument('--author', default='Unknown', help='Book author')

    args = parser.parse_args()

    imaginize_dir = Path(args.base_dir) if Path(args.base_dir).name.startswith('imaginize_') else None

    print(f"📚 Compiling CBZ from: {args.base_dir}")
    print(f"📄 Output file: {args.output_file}")

    images = collect_images(args.base_dir)

    if not images:
        print("❌ No images found!")
        sys.exit(1)

    print(f"📸 Found {len(images)} images")
    create_cbz(images, args.output_file, title=args.title, author=args.author, imaginize_dir=imaginize_dir)
